import { FormEvent, useEffect, useState } from "react";
import { CalendarDays, Edit3, Plus, Ship, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
import type { Container, Voyage } from "@/types";

const blank = { vessel_name: "", port_of_loading: "Nansha, China", port_of_discharge: "Tema, Ghana", etd: "", eta: "", atd: "", ata: "", status: "scheduled" as Voyage["status"] };

export default function Voyages() {
  const [voyages, setVoyages] = useState<Voyage[]>([]);
  const [containers, setContainers] = useState<Container[]>([]);
  const [form, setForm] = useState(blank);
  const [editing, setEditing] = useState<string | null>(null);
  const load = async () => { const [{ data: voyageRows }, { data: containerRows }] = await Promise.all([supabase.from("voyages").select("*").order("etd", { ascending: false }), supabase.from("containers").select("*").order("created_at", { ascending: false })]); setVoyages((voyageRows || []) as Voyage[]); setContainers((containerRows || []) as Container[]); };
  useEffect(() => { load(); }, []);
  const save = async (event: FormEvent) => { event.preventDefault(); const payload = { ...form, atd: form.atd || null, ata: form.ata || null }; const query = editing ? supabase.from("voyages").update(payload).eq("id", editing) : supabase.from("voyages").insert(payload); const { error } = await query; if (error) toast.error(error.message); else { toast.success(editing ? "Voyage updated" : "Voyage created"); setForm(blank); setEditing(null); load(); } };
  const edit = (voyage: Voyage) => { setEditing(voyage.id); setForm({ vessel_name: voyage.vessel_name, port_of_loading: voyage.port_of_loading, port_of_discharge: voyage.port_of_discharge, etd: voyage.etd, eta: voyage.eta, atd: voyage.atd || "", ata: voyage.ata || "", status: voyage.status }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const remove = async (id: string) => { const { error } = await supabase.from("voyages").delete().eq("id", id); if (error) toast.error(error.message); else load(); };
  const updateStatus = async (id: string, status: Voyage["status"]) => { const { error } = await supabase.from("voyages").update({ status }).eq("id", id); if (error) toast.error(error.message); else { toast.success(status === "departed" ? "Voyage and assigned containers marked departed" : "Voyage status updated"); load(); } };
  const assignContainer = async (containerId: string, voyageId: string) => { const { error } = await supabase.from("containers").update({ voyage_id: voyageId }).eq("id", containerId).eq("status", "open"); if (error) toast.error(error.message); else { toast.success("Container assigned to voyage"); load(); } };

  return <div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#ed1c2a]">Sailing desk</p><h1 className="mt-2 text-3xl font-black">Voyage management</h1><p className="mt-2 text-slate-500">Plan sailings, assign open containers, and publish milestone changes.</p>
    <form onSubmit={save} className="mt-8 rounded-3xl border bg-white p-6"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-red-50 text-[#ed1c2a]">{editing ? <Edit3 /> : <Plus />}</div><h2 className="font-black">{editing ? "Edit voyage" : "Create voyage"}</h2></div><div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-4"><Field label="Vessel name" value={form.vessel_name} onChange={(v) => setForm({ ...form, vessel_name: v })} /><Field label="Port of loading" value={form.port_of_loading} onChange={(v) => setForm({ ...form, port_of_loading: v })} /><Field label="Port of discharge" value={form.port_of_discharge} onChange={(v) => setForm({ ...form, port_of_discharge: v })} /><Field label="ETD" type="date" value={form.etd} onChange={(v) => setForm({ ...form, etd: v })} /><Field label="ETA" type="date" value={form.eta} onChange={(v) => setForm({ ...form, eta: v })} /><Field label="ATD (optional)" type="date" value={form.atd} onChange={(v) => setForm({ ...form, atd: v })} /><Field label="ATA (optional)" type="date" value={form.ata} onChange={(v) => setForm({ ...form, ata: v })} /><div><Label>Status</Label><Select value={form.status} onValueChange={(v) => setForm({ ...form, status: v as Voyage["status"] })}><SelectTrigger className="mt-2 h-11 rounded-xl"><SelectValue /></SelectTrigger><SelectContent>{["scheduled","departed","in_transit","arrived"].map((status) => <SelectItem key={status} value={status}>{status.replace("_", " ")}</SelectItem>)}</SelectContent></Select></div></div><div className="mt-5 flex gap-3"><Button className="rounded-xl bg-[#ed1c2a] font-black hover:bg-[#c91521]">{editing ? "Save voyage" : "Create voyage"}</Button>{editing && <Button type="button" variant="ghost" onClick={() => { setEditing(null); setForm(blank); }}>Cancel</Button>}</div></form>
    <div className="mt-8 grid gap-5 lg:grid-cols-2">{voyages.map((voyage) => { const assigned = containers.filter((container) => container.voyage_id === voyage.id); return <article key={voyage.id} className="rounded-3xl border bg-white p-6"><div className="flex items-start justify-between"><div className="flex items-center gap-4"><div className="grid size-12 place-items-center rounded-2xl bg-[#062542] text-white"><Ship /></div><div><h2 className="text-xl font-black">{voyage.vessel_name}</h2><p className="text-sm text-slate-500">{voyage.port_of_loading} → {voyage.port_of_discharge}</p></div></div><Badge className="capitalize bg-red-50 text-[#c91521] hover:bg-red-50">{voyage.status.replace("_", " ")}</Badge></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#f3f7fb] p-4"><p className="text-xs text-slate-500">Departure</p><p className="mt-1 font-bold">{new Date(voyage.atd || voyage.etd).toLocaleDateString()}</p></div><div className="rounded-xl bg-[#f3f7fb] p-4"><p className="text-xs text-slate-500">Arrival</p><p className="mt-1 font-bold">{new Date(voyage.ata || voyage.eta).toLocaleDateString()}</p></div></div><div className="mt-5 flex items-center justify-between"><p className="text-sm font-bold">{assigned.length} assigned container{assigned.length === 1 ? "" : "s"}</p><div className="flex gap-2"><Button size="icon" variant="outline" onClick={() => edit(voyage)}><Edit3 className="size-4" /></Button><Button size="icon" variant="outline" className="text-[#ed1c2a]" onClick={() => remove(voyage.id)}><Trash2 className="size-4" /></Button></div></div><Select value={voyage.status} onValueChange={(v) => updateStatus(voyage.id, v as Voyage["status"])}><SelectTrigger className="mt-4 h-10 rounded-xl"><SelectValue /></SelectTrigger><SelectContent>{["scheduled","departed","in_transit","arrived"].map((status) => <SelectItem key={status} value={status}>{status.replace("_", " ")}</SelectItem>)}</SelectContent></Select></article>; })}</div>
    <section className="mt-8 rounded-3xl border bg-white p-6"><div className="flex items-center gap-3"><CalendarDays className="text-[#ed1c2a]" /><h2 className="text-xl font-black">Unassigned open containers</h2></div><div className="mt-5 grid gap-4 md:grid-cols-2">{containers.filter((container) => container.status === "open" && !container.voyage_id).map((container) => <div key={container.id} className="flex flex-col justify-between gap-4 rounded-2xl bg-[#f3f7fb] p-4 sm:flex-row sm:items-center"><div><p className="font-mono font-black">{container.seal_number}</p><p className="text-sm text-slate-500">{container.warehouse} · {container.destination_lane}</p></div><Select onValueChange={(value) => assignContainer(container.id, value)}><SelectTrigger className="w-full bg-white sm:w-56"><SelectValue placeholder="Assign voyage" /></SelectTrigger><SelectContent>{voyages.filter((voyage) => voyage.status === "scheduled").map((voyage) => <SelectItem key={voyage.id} value={voyage.id}>{voyage.vessel_name}</SelectItem>)}</SelectContent></Select></div>)}</div></section>
  </div>;
}
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <div><Label>{label}</Label><Input required={!label.includes("optional")} type={type} value={value} onChange={(e) => onChange(e.target.value)} className="mt-2 h-11 rounded-xl" /></div>; }
