// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vtmltgqdegrhhoxtegkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_KB-lDtkSoC2NAyHfn1eqBQ_pPSab2fX";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
